name: shared-ci-quality-check

on:
  workflow_call:

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Basic CI check
        run: echo "Running Shared CI Quality Check"

      # These steps are only for Node.js projects
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint (optional)
      - name: Run lint
        run: npm run lint

      # Run tests (optional)
      - name: Run tests
        run: npm test
