name: Context Demo

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
